"use client";

// components/RoadmapTimeline.tsx

import { useMemo, useState } from "react";
import {
  CalendarDays,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Circle,
  Flag,
  Rocket,
  Sparkles,
  Target,
} from "lucide-react";
import { RoadmapItem } from "@/lib/reportSchema";
import { ProvenanceBadge } from "./ProvenanceBadge";

type RoadmapTimelineProps = {
  roadmap: RoadmapItem[];

  /**
   * Identifies whether the roadmap narrative was generated by AI
   * or supplied through EmpresaFi's local recovery path.
   */
  generationMode?: "ai" | "fallback";
};

type TimelineStage = RoadmapItem & {
  index: number;
  shortLabel: string;
  phaseLabel: string;
  icon: React.ComponentType<{ className?: string }>;
};

/**
 * Returns the display details associated with each roadmap period.
 */
function getStageDetails(
  period: RoadmapItem["period"],
  index: number
): Pick<TimelineStage, "shortLabel" | "phaseLabel" | "icon"> {
  switch (period) {
    case "30 Days":
      return {
        shortLabel: "30D",
        phaseLabel: "Validate",
        icon: Target,
      };

    case "90 Days":
      return {
        shortLabel: "90D",
        phaseLabel: "Launch",
        icon: Rocket,
      };

    case "365 Days":
      return {
        shortLabel: "1Y",
        phaseLabel: "Scale",
        icon: Flag,
      };

    default:
      return {
        shortLabel: `P${index + 1}`,
        phaseLabel: "Execute",
        icon: CalendarDays,
      };
  }
}

/**
 * Converts the existing report roadmap into a UI-ready timeline.
 */
function buildTimelineStages(
  roadmap: RoadmapItem[]
): TimelineStage[] {
  return roadmap.map((item, index) => ({
    ...item,
    index,
    ...getStageDetails(item.period, index),
  }));
}

/**
 * Interactive roadmap built from EmpresaFi's existing 30, 90,
 * and 365-day execution plan.
 *
 * Connector lines are rendered only between milestones so they do not
 * pass through milestone icons.
 */
export function RoadmapTimeline({
  roadmap,
  generationMode = "ai",
}: RoadmapTimelineProps) {
  const stages = useMemo(
    () => buildTimelineStages(roadmap),
    [roadmap]
  );

  const [activeIndex, setActiveIndex] = useState(0);

  if (stages.length === 0) {
    return null;
  }

  const safeActiveIndex = Math.min(
    activeIndex,
    stages.length - 1
  );

  const activeStage = stages[safeActiveIndex];
  const ActiveIcon = activeStage.icon;

  /**
   * Selects a roadmap stage while keeping the index valid.
   */
  function selectStage(index: number) {
    const nextIndex = Math.max(
      0,
      Math.min(index, stages.length - 1)
    );

    setActiveIndex(nextIndex);
  }

  return (
    <section className="venture-panel rounded-[2rem] p-6 text-white md:p-8">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
        <div className="max-w-3xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1.5 text-xs font-medium text-violet-200">
            <Sparkles className="h-3.5 w-3.5" />
            Execution Intelligence
          </div>

          <h2 className="mt-5 text-2xl font-semibold tracking-tight md:text-4xl">
            Interactive execution roadmap
          </h2>

          <p className="mt-3 max-w-2xl text-sm leading-7 text-white/50 md:text-base">
            Explore the venture&apos;s validation, launch, and scaling
            milestones across the first year.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <ProvenanceBadge
            type={
              generationMode === "fallback"
                ? "local_recovery"
                : "ai_generated"
            }
            showConfidence={false}
          />

          <div className="rounded-2xl border border-white/8 bg-black/15 px-4 py-3">
            <p className="text-[10px] uppercase tracking-[0.2em] text-white/35">
              Current milestone
            </p>

            <p className="mt-1 text-lg font-semibold">
              {activeStage.period}
            </p>
          </div>
        </div>
      </div>

      <div className="mt-8 rounded-3xl border border-white/8 bg-black/10 p-5 md:p-7">
        <div className="relative">
          <div className="relative grid gap-3 md:grid-cols-3 md:gap-6">
            {stages.map((stage, index) => {
              const StageIcon = stage.icon;
              const isActive =
                index === safeActiveIndex;
              const isCompleted =
                index < safeActiveIndex;
              const isConnectorCompleted =
                index < safeActiveIndex;

              return (
                <div
                  key={`${stage.period}-${stage.title}`}
                  className="relative"
                >
                  {index < stages.length - 1 && (
                    <div className="absolute left-[calc(50%+2rem)] right-[calc(-50%+2rem)] top-6 z-0 hidden h-1 overflow-hidden rounded-full bg-white/5 md:block">
                      <div
                        className={`h-full rounded-full transition-all duration-500 ${
                          isConnectorCompleted
                            ? "w-full bg-gradient-to-r from-emerald-400 via-violet-400 to-cyan-400"
                            : isActive
                              ? "w-1/2 bg-gradient-to-r from-violet-500 to-fuchsia-400"
                              : "w-0"
                        }`}
                      />
                    </div>
                  )}

                  <button
                    type="button"
                    onClick={() =>
                      selectStage(index)
                    }
                    aria-pressed={isActive}
                    className={`group relative z-10 flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition-all duration-300 md:flex-col md:border-0 md:bg-transparent md:p-0 md:text-center ${
                      isActive
                        ? "border-violet-400/25 bg-violet-400/[0.08]"
                        : "border-white/6 bg-white/[0.02]"
                    }`}
                  >
                    <span
                      className={`relative z-20 flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border transition-all duration-300 md:rounded-full ${
                        isActive
                          ? "scale-110 border-violet-300/40 bg-[#221c3b] text-violet-100 shadow-[0_0_30px_rgba(139,92,246,0.25)]"
                          : isCompleted
                            ? "border-emerald-400/30 bg-[#092d2b] text-emerald-200"
                            : "border-white/10 bg-[#0b1020] text-white/35 group-hover:border-white/20 group-hover:text-white/60"
                      }`}
                    >
                      {isCompleted ? (
                        <CheckCircle2 className="h-5 w-5" />
                      ) : (
                        <StageIcon className="h-5 w-5" />
                      )}
                    </span>

                    <span className="min-w-0 md:mt-4">
                      <span className="block text-[10px] font-semibold uppercase tracking-[0.2em] text-white/35">
                        {stage.phaseLabel}
                      </span>

                      <span
                        className={`mt-1 block text-sm font-semibold transition-colors ${
                          isActive
                            ? "text-white"
                            : "text-white/55"
                        }`}
                      >
                        {stage.period}
                      </span>

                      <span className="mt-1 block truncate text-xs text-white/35 md:max-w-[13rem]">
                        {stage.title}
                      </span>
                    </span>
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      <div className="mt-5 grid gap-5 xl:grid-cols-[0.7fr_1.3fr]">
        <article className="relative overflow-hidden rounded-3xl border border-violet-400/15 bg-violet-400/[0.06] p-5 md:p-6">
          <div className="pointer-events-none absolute right-[-4rem] top-[-4rem] h-40 w-40 rounded-full bg-violet-500/15 blur-3xl" />

          <div className="relative">
            <div className="flex items-start justify-between gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-violet-400/25 bg-violet-400/10 text-violet-200">
                <ActiveIcon className="h-5 w-5" />
              </div>

              <span className="rounded-full border border-white/8 bg-black/15 px-3 py-1.5 text-xs text-white/40">
                Stage {safeActiveIndex + 1} of{" "}
                {stages.length}
              </span>
            </div>

            <p className="mt-6 text-xs font-semibold uppercase tracking-[0.22em] text-violet-200/60">
              {activeStage.phaseLabel} phase
            </p>

            <h3 className="mt-2 text-2xl font-semibold tracking-tight">
              {activeStage.title}
            </h3>

            <p className="mt-3 text-sm leading-6 text-white/45">
              Complete these milestones during the{" "}
              {activeStage.period.toLowerCase()} stage
              before moving into the next phase.
            </p>

            <div className="roadmap-interactive-controls mt-7 flex items-center justify-between">
              <button
                type="button"
                onClick={() =>
                  selectStage(safeActiveIndex - 1)
                }
                disabled={safeActiveIndex === 0}
                className="inline-flex items-center gap-2 rounded-xl border border-white/8 bg-white/[0.03] px-4 py-2.5 text-sm text-white/55 transition hover:bg-white/[0.07] disabled:cursor-not-allowed disabled:opacity-30"
              >
                <ChevronLeft className="h-4 w-4" />
                Previous
              </button>

              <button
                type="button"
                onClick={() =>
                  selectStage(safeActiveIndex + 1)
                }
                disabled={
                  safeActiveIndex ===
                  stages.length - 1
                }
                className="inline-flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-400/10 px-4 py-2.5 text-sm text-violet-100 transition hover:bg-violet-400/15 disabled:cursor-not-allowed disabled:opacity-30"
              >
                Next
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        </article>

        <article className="rounded-3xl border border-white/8 bg-black/10 p-5 md:p-6">
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/35">
                Milestone actions
              </p>

              <p className="mt-2 text-sm text-white/45">
                Priority activities for this execution stage.
              </p>
            </div>

            <div className="flex items-center gap-2 text-xs text-white/35">
              <CalendarDays className="h-4 w-4" />
              {activeStage.period}
            </div>
          </div>

          <div className="mt-6 space-y-3">
            {activeStage.actions.map(
              (action, index) => (
                <div
                  key={`${activeStage.period}-${action}-${index}`}
                  className="group flex gap-4 rounded-2xl border border-white/6 bg-white/[0.025] p-4 transition hover:border-violet-400/15 hover:bg-violet-400/[0.04]"
                >
                  <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-violet-400/15 bg-violet-400/10 text-xs font-semibold text-violet-200">
                    {String(index + 1).padStart(
                      2,
                      "0"
                    )}
                  </span>

                  <div className="min-w-0 flex-1">
                    <p className="text-sm leading-6 text-white/60">
                      {action}
                    </p>

                    <div className="mt-3 flex items-center gap-2 text-[11px] uppercase tracking-[0.15em] text-white/25">
                      <Circle className="h-3 w-3" />
                      Planned action
                    </div>
                  </div>
                </div>
              )
            )}
          </div>
        </article>
      </div>

      <div className="roadmap-interactive-controls mt-5 rounded-3xl border border-white/8 bg-white/[0.025] p-5">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/35">
              Execution progress
            </p>

            <p className="mt-2 text-sm leading-6 text-white/45">
              Select each milestone to review the
              complete first-year execution plan.
            </p>
          </div>

          <div className="flex items-center gap-2">
            {stages.map((stage, index) => (
              <button
                key={`progress-${stage.period}`}
                type="button"
                onClick={() =>
                  selectStage(index)
                }
                aria-label={`Open ${stage.period} roadmap stage`}
                className={`h-2.5 rounded-full transition-all duration-300 ${
                  index === safeActiveIndex
                    ? "w-10 bg-violet-400"
                    : index < safeActiveIndex
                      ? "w-6 bg-emerald-400/70"
                      : "w-6 bg-white/10 hover:bg-white/20"
                }`}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}