// lib/provenance.ts

export type ProvenanceType =
  | "deterministic"
  | "ai_generated"
  | "ai_estimate"
  | "modeled"
  | "planning_estimate"
  | "local_recovery";

export type ProvenanceConfig = {
  type: ProvenanceType;
  label: string;
  description: string;
  confidence?: number;
};

/**
 * Returns user-facing information for each EmpresaFi intelligence source.
 */
export function getProvenanceConfig(
  type: ProvenanceType,
  confidence?: number
): ProvenanceConfig {
  switch (type) {
    case "deterministic":
      return {
        type,
        label: "Deterministic Engine",
        description:
          "Calculated by EmpresaFi using stable and repeatable scoring logic.",
        confidence,
      };

    case "ai_generated":
      return {
        type,
        label: "AI Generated",
        description:
          "Generated by the EmpresaFi AI report engine using the submitted venture context.",
        confidence,
      };

    case "ai_estimate":
      return {
        type,
        label: "AI Strategic Estimate",
        description:
          "Produced through AI strategic reasoning and not presented as independently verified live research.",
        confidence,
      };

    case "modeled":
      return {
        type,
        label: "Modeled Projection",
        description:
          "Calculated from EmpresaFi planning formulas and report assumptions.",
        confidence,
      };

    case "planning_estimate":
      return {
        type,
        label: "Planning Estimate",
        description:
          "Illustrative estimate intended for early-stage business planning.",
        confidence,
      };

    case "local_recovery":
      return {
        type,
        label: "Local Recovery",
        description:
          "Generated from EmpresaFi's dependable local fallback when AI output was unavailable or incomplete.",
        confidence,
      };
  }
}